export const BRAND = {
  mark: "/brand/mascot-mark.png",
  jump: "/brand/mascot-jump.png",
  jumpHi: "/brand/wave-hi.png",
  hoodie: "/brand/mascot-hoodie.png",
  coffee: "/brand/mascot-coffee.png",
  laptop: "/brand/mascot-laptop.png",
  hero: "/brand/hero.jpg",
  wave: "/brand/wave.png",
  waveSky: "/brand/wave.png",
  poses: "/brand/poses.png",
  idle: "/brand/idle.png",
  idleStand: "/brand/idle-stand.png",
  jumpStand: "/brand/jump-stand.png",
  laptopStand: "/brand/laptop-stand.png",
  dock: "/brand/dock.png",
  empty: "/brand/empty.png",
  sheets: "/brand/sheets.png",
} as const;
