export const TOKEN_NAME = 'GAMESTOP GIRL'
export const TICKER = '$GMEGIRL'
export const PAIR = '$GME'
export const DESK = 'Robinhood'
export const X_HANDLE = '@gmegirlcoin'
export const X_URL = 'https://x.com/gmegirlcoin'
export const CA = '0xb81db48dc9d80597bad3f4f33aef42fed880e443'
export const BUY_URL = `https://gmgn.ai/robinhood/token/${CA}`

export const LINE = 'The GME Girl is finally paired with GME.'

export const ABOUT = [
  'GameStop Girl became one of the most recognizable faces of the GameStop retail era.',
  'Now the meme, the stock and the rewards are finally connected in one market.',
] as const

export const FEE_HEAD = '100% OF CREATOR FEES GO TO RILIE'
export const FEE_BODY =
  'Every creator fee generated by $GMEGIRL goes to Rilie Huntley’s ETH address.'
export const RILIE_ETH = '0x9E3137e0305750B0C2DdBA05Bf42Aee0DdD54169'

export const TAPE = [
  TICKER,
  PAIR,
  X_HANDLE,
  'GAMESTOP GIRL',
  DESK,
  TICKER,
  PAIR,
  'CA',
] as const
